"use client";

import {
  type CSSVariablesResolver,
  createTheme,
  type MantineColorsTuple,
  type MantineThemeOther,
} from "@mantine/core";

// The Material 3 token set generated by Stitch from the source accent #c2603a,
// copied verbatim from the "Parametric Tray Builder" design so the values here
// stay traceable to the design rather than being eyeballed. Nothing outside
// this file reads STITCH directly — it exists to build the tuples and the
// custom properties below, which is what call sites use.
const STITCH = {
  background: "#fff8f3",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
  inverseOnSurface: "#f6f0ea",
  inversePrimary: "#ffb59b",
  inverseSurface: "#32302d",
  onError: "#ffffff",
  onErrorContainer: "#93000a",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#fffbff",
  onPrimaryFixed: "#380d00",
  onPrimaryFixedVariant: "#7d2d0a",
  onSecondaryContainer: "#795354",
  onSurface: "#1d1b18",
  onSurfaceVariant: "#56423c",
  onTertiaryFixed: "#1e1b12",
  onTertiaryFixedVariant: "#4a473b",
  outline: "#89726a",
  outlineVariant: "#dcc1b8",
  primary: "#99411e",
  primaryContainer: "#b85933",
  primaryFixed: "#ffdbcf",
  primaryFixedDim: "#ffb59b",
  secondary: "#7b5455",
  secondaryContainer: "#fdcbcb",
  surface: "#fff8f3",
  surfaceContainer: "#f3ede7",
  surfaceContainerHigh: "#ede7e2",
  surfaceContainerHighest: "#e7e1dc",
  surfaceContainerLow: "#f9f2ed",
  surfaceContainerLowest: "#ffffff",
  surfaceDim: "#dfd9d4",
  surfaceVariant: "#e7e1dc",
  tertiary: "#605c4f",
  tertiaryContainer: "#797467",
  tertiaryFixed: "#e9e2d2",
  tertiaryFixedDim: "#cdc6b6",
  // Not an M3 token: the graph-paper rule the design draws behind the plan view.
  gridRule: "#d9d2c2",
} as const;

// M3 names a flat set of roles; Mantine wants ordered ramps. These three tuples
// re-shape the tokens above into light -> dark ramps so ordinary Mantine props
// (`c="sand.8"`, `bg="sand.1"`) keep behaving the way the shade number implies.
//
// `rust` is the primary ramp. Shade 6 is Stitch's `primary` and stays the
// primaryShade, so `color="rust"` and every default-primary control land on it.
const rust: MantineColorsTuple = [
  STITCH.onPrimaryContainer, // 0 #fffbff
  STITCH.primaryFixed, // 1 #ffdbcf
  STITCH.primaryFixedDim, // 2 #ffb59b
  "#f08f6b", // 3 — interpolated
  "#d9713f", // 4 — interpolated
  STITCH.primaryContainer, // 5 #b85933
  STITCH.primary, // 6 #99411e — primaryShade
  STITCH.onPrimaryFixedVariant, // 7 #7d2d0a
  "#5e2208", // 8 — interpolated
  STITCH.onPrimaryFixed, // 9 #380d00
];

// `sand` carries every neutral the UI needs, in one continuous ramp: the paper
// surfaces (0-5), the two outline weights (6-7), then the two ink weights
// (8 secondary text, 9 body text). Keeping it monotonic is what lets a single
// tuple serve backgrounds, hairlines, and type.
const sand: MantineColorsTuple = [
  STITCH.surfaceContainerLowest, // 0 #ffffff
  STITCH.surface, // 1 #fff8f3 — page background
  STITCH.surfaceContainerLow, // 2 #f9f2ed
  STITCH.surfaceContainer, // 3 #f3ede7
  STITCH.surfaceContainerHigh, // 4 #ede7e2
  STITCH.surfaceVariant, // 5 #e7e1dc
  STITCH.outlineVariant, // 6 #dcc1b8 — the hairline border
  STITCH.outline, // 7 #89726a
  STITCH.onSurfaceVariant, // 8 #56423c — labels, secondary text
  STITCH.onSurface, // 9 #1d1b18 — body ink
];

// `stone` is the tertiary ramp. It exists for the print-estimate card, which
// the design sets on `tertiary-fixed` to sit apart from the paper surfaces.
const stone: MantineColorsTuple = [
  "#f7f4ec", // 0 — interpolated
  STITCH.tertiaryFixed, // 1 #e9e2d2
  STITCH.tertiaryFixedDim, // 2 #cdc6b6
  "#b4ad9d", // 3 — interpolated
  "#9b9484", // 4 — interpolated
  "#8a8474", // 5 — interpolated
  STITCH.tertiaryContainer, // 6 #797467
  STITCH.tertiary, // 7 #605c4f
  STITCH.onTertiaryFixedVariant, // 8 #4a473b
  STITCH.onTertiaryFixed, // 9 #1e1b12
];

// The design's named type scale. Sizes and tracking come straight from the
// Stitch typography tokens; the two families resolve to the fonts loaded in
// layout.tsx. Exposed as CSS custom properties (see cssVariablesResolver) so
// components can spread a token instead of restating five properties.
const SANS = "var(--font-fira), system-ui, sans-serif";
const MONO = "var(--font-space-mono), ui-monospace, monospace";

/** `header-section` — the uppercase monospace rule over every rail section and
 * preview-panel badge. This is the app's one section-heading treatment. */
export const HEADER_SECTION = {
  fontFamily: MONO,
  fontSize: "12px",
  lineHeight: "16px",
  fontWeight: 700,
  letterSpacing: "0.1em",
  textTransform: "uppercase",
} as const;

/** `dimension-md` — the editable numeric readouts inside parameter capsules. */
export const DIMENSION_MD = {
  fontFamily: MONO,
  fontSize: "14px",
  lineHeight: "20px",
  fontWeight: 400,
} as const;

/** `dimension-sm` — unit suffixes, dimension lines, footer text. */
export const DIMENSION_SM = {
  fontFamily: MONO,
  fontSize: "12px",
  lineHeight: "16px",
  fontWeight: 400,
} as const;

/** `label-xs` — the smallest sans label, used on toggle chips. */
export const LABEL_XS = {
  fontFamily: SANS,
  fontSize: "11px",
  lineHeight: "14px",
  fontWeight: 500,
} as const;

// Semantic one-offs that don't belong to any ramp. They reach PlanView and
// globals.css — neither of which uses Mantine components — as custom properties.
const other = {
  gridRule: STITCH.gridRule,
  inverseSurface: STITCH.inverseSurface,
  errorContainer: STITCH.errorContainer,
  onErrorContainer: STITCH.onErrorContainer,
  secondary: STITCH.secondary,
  secondaryContainer: STITCH.secondaryContainer,
  onSecondaryContainer: STITCH.onSecondaryContainer,
} satisfies MantineThemeOther;

export const theme = createTheme({
  colors: { rust, sand, stone },
  primaryColor: "rust",
  primaryShade: 6,
  fontFamily: SANS,
  fontFamilyMonospace: MONO,
  headings: {
    fontFamily: SANS,
    sizes: {
      // `display-lg` — the model name at the top of the workspace.
      h1: { fontSize: "32px", lineHeight: "1.2", fontWeight: "600" },
    },
  },
  // Matches the design's `body-ui` (14) / `dimension-sm` (12) / `label-xs` (11).
  fontSizes: { xs: "11px", sm: "12px", md: "14px", lg: "16px", xl: "20px" },
  lineHeights: { xs: "14px", sm: "16px", md: "20px", lg: "24px", xl: "28px" },
  // The design's spacing scale, which is a 4px grid rather than Mantine's default.
  spacing: { xs: "4px", sm: "8px", md: "16px", lg: "24px", xl: "40px" },
  // Stitch's roundness is ROUND_FULL: cards take a generous corner, controls go
  // fully round. `md` is the card default; `xl` reads as a pill at control heights.
  radius: { xs: "4px", sm: "8px", md: "16px", lg: "32px", xl: "48px" },
  defaultRadius: "md",
  black: STITCH.onSurface,
  white: STITCH.surfaceContainerLowest,
  components: {
    // Controls are pills throughout the design.
    Button: { defaultProps: { radius: 9999 } },
    ActionIcon: { defaultProps: { radius: 9999 } },
    // Covers the label of every wrapped input, including Radio.Group's — the
    // design labels fields in body text, not the section rule.
    InputWrapper: {
      styles: {
        label: { fontSize: "14px", fontWeight: 400, color: "var(--mantine-color-sand-8)" },
      },
    },
    Checkbox: { styles: { label: { fontSize: "14px" } } },
  },
  other,
});

// The icon palette. Every colour in `src/app/icons` resolves through one of
// these roles, so the dimension sketches and closure icons re-tint with the
// theme instead of carrying baked-in hexes. They're derived from the ramps
// above rather than from STITCH directly: changing `rust` or `sand` moves the
// artwork with it. The .svg design sources repeat these as `var(--tt-icon-*,
// #hex)` fallbacks so they still render correctly opened on their own.
const ICON_TOKENS = {
  /** Primary geometry outline — the silhouette of the part being measured. */
  "--tt-icon-line": "var(--mantine-color-sand-9)",
  /** Reference geometry: extension lines, hidden edges, inner outlines. */
  "--tt-icon-line-soft": "var(--mantine-color-sand-7)",
  /** Material wash inside a sectioned solid. */
  "--tt-icon-fill": "color-mix(in srgb, var(--mantine-color-rust-6) 8%, transparent)",
  /** The same wash where two sections overlap and must read denser. */
  "--tt-icon-fill-strong": "color-mix(in srgb, var(--mantine-color-rust-6) 14%, transparent)",
  /** Measure arrows, dimension lines, radius markers — the quantity itself. */
  "--tt-icon-accent": "var(--mantine-color-rust-6)",
  /** Accent as a fill (the interference hatch). */
  "--tt-icon-accent-soft": "color-mix(in srgb, var(--mantine-color-rust-6) 30%, transparent)",
  /** Knockout behind the motion arrow — set to the surface the icon sits on. */
  "--tt-icon-halo": "var(--mantine-color-sand-0)",
  // The isometric tray in the closure icons: four faces, lightest on top.
  "--tt-icon-face-top": "var(--mantine-color-sand-2)",
  "--tt-icon-face-left": "var(--mantine-color-sand-4)",
  "--tt-icon-face-right": "var(--mantine-color-sand-5)",
  "--tt-icon-face-inner": "var(--mantine-color-sand-6)",
  /** The closure (lid / cover / sliding panel) drawn over the tray. */
  "--tt-icon-closure": "var(--tt-secondary)",
  "--tt-icon-closure-fill": "color-mix(in srgb, var(--tt-secondary) 10%, transparent)",
  "--tt-icon-closure-fill-strong": "color-mix(in srgb, var(--tt-secondary) 18%, transparent)",
  /** The arrow showing how the closure goes on. */
  "--tt-icon-motion": "var(--mantine-color-rust-6)",
} as const;

// Publishes the non-ramp tokens as custom properties. PlanView draws its own
// 2D layout and globals.css styles hover states — both need theme values
// without a Mantine component to hang props on, and this is the seam for that.
export const cssVariablesResolver: CSSVariablesResolver = (t) => ({
  variables: {
    "--tt-grid-rule": t.other.gridRule,
    "--tt-inverse-surface": t.other.inverseSurface,
    "--tt-error-container": t.other.errorContainer,
    "--tt-on-error-container": t.other.onErrorContainer,
    "--tt-secondary": t.other.secondary,
    "--tt-secondary-container": t.other.secondaryContainer,
    "--tt-on-secondary-container": t.other.onSecondaryContainer,
    ...ICON_TOKENS,
  },
  light: {},
  dark: {},
});
